### ISSUE TITLE
TypeError: '_Ed25519PrivateKey' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by lwhile** [learnforpractice/mixin-python#3]
Thanks for your hard work first.

I initialized a `MixinBotApi` with `ed25519` private key. But code raised the `TypeError: '_Ed25519PrivateKey' object cannot be interpreted as an integer` when I called `gen_encrypted_pin`.

Here is the stack information

```text
Traceback (most recent call last):
  ......
  File "venv/lib/python3.9/site-packages/pymixin/mixin_bot_api.py", line 114, in gen_encrypted_pin
    privKeyObj = RSA.importKey(self.private_key)
  File "venv/lib/python3.9/site-packages/Crypto/PublicKey/RSA.py", line 756, in import_key
    extern_key = tobytes(extern_key)
  File "venv/lib/python3.9/site-packages/Crypto/Util/py3compat.py", line 134, in tobytes
    return bytes([s])
TypeError: '_Ed25519PrivateKey' object cannot be interpreted as an integer
```

**Comment by learnforpractice** [comment]
It’s a bug, avoid using verify_ping before it’s been fixed.
